# filename: app/core/db.py

import os
import logging
import hashlib
import json

from sqlalchemy.ext.asyncio import (
    create_async_engine,
    AsyncSession,
    async_sessionmaker,
)
from sqlalchemy.orm import declarative_base
from sqlalchemy.exc import ArgumentError

# -------------------------------
# LOGGING
# -------------------------------
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("app.core.db")

# -------------------------------
# BASE
# -------------------------------
Base = declarative_base()

# -------------------------------
# DATABASE URL (RAILWAY SAFE)
# -------------------------------
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

if not DATABASE_URL:
    raise RuntimeError(
        "❌ DATABASE_URL is not set. "
        "Ensure it is defined in Railway variables."
    )

# Normalize legacy postgres URLs if any
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace(
        "postgres://", "postgresql+asyncpg://", 1
    )
elif DATABASE_URL.startswith("postgresql://") and "+asyncpg" not in DATABASE_URL:
    DATABASE_URL = DATABASE_URL.replace(
        "postgresql://", "postgresql+asyncpg://", 1
    )

# 🚨 Detect uninterpolated Railway placeholders
if "${{" in DATABASE_URL:
    raise RuntimeError(
        "❌ DATABASE_URL contains unresolved placeholders. "
        "Railway does NOT substitute ${{...}} at runtime.\n"
        "Please use Railway's autogenerated DATABASE_URL variable directly."
    )

# -------------------------------
# ENGINE & SESSION
# -------------------------------
try:
    engine = create_async_engine(
        DATABASE_URL,
        pool_pre_ping=True,
        future=True,
    )
except ArgumentError as e:
    raise RuntimeError(
        f"❌ Invalid DATABASE_URL format:\n{DATABASE_URL}"
    ) from e

SessionLocal = async_sessionmaker(
    bind=engine,
    class_=AsyncSession,
    expire_on_commit=False,
)

# -------------------------------
# SCHEMA HASH SUPPORT
# -------------------------------
_SCHEMA_HASH_FILE = "/tmp/schema.hash"

async def compute_schema_hash():
    import app.core.models as models
    tables = sorted(models.Base.metadata.tables.keys())
    return hashlib.sha256(json.dumps(tables).encode()).hexdigest()

async def init_models():
    """
    Rebuild tables only if schema changes.
    Safe for production rollout.
    """
    import app.core.models as models

    async with engine.begin() as conn:
        current_hash = await compute_schema_hash()
        previous_hash = None

        if os.path.exists(_SCHEMA_HASH_FILE):
            with open(_SCHEMA_HASH_FILE, "r") as f:
                previous_hash = f.read().strip()

        if current_hash != previous_hash:
            await conn.run_sync(models.Base.metadata.drop_all)
            await conn.run_sync(models.Base.metadata.create_all)
            with open(_SCHEMA_HASH_FILE, "w") as f:
                f.write(current_hash)
            logger.warning("⚠️ Database schema updated (tables rebuilt)")
        else:
            logger.info("✅ Database schema unchanged")

# -------------------------------
# SESSION DEPENDENCIES
# -------------------------------
async def get_db():
    async with SessionLocal() as session:
        try:
            yield session
        finally:
            await session.close()

# ✅ BACKWARD‑COMPATIBLE ALIAS
# DO NOT REMOVE — required by reviews.py and others
get_session = get_db
